<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/app_models.php';
require_once __DIR__ . '/includes/csrf.php';
require_once __DIR__ . '/includes/site_data.php';
csrf_start();
$pageTitle='Анкета мастера — '.APP_NAME; $errors=[]; $done=false;
if ($_SERVER['REQUEST_METHOD']==='POST') {
  if (!csrf_verify($_POST['csrf'] ?? '')) $errors[]='Ошибка безопасности. Обновите страницу.';
  else {
    $name=trim((string)($_POST['name'] ?? '')); $email=trim((string)($_POST['email'] ?? '')); $phone=trim((string)($_POST['phone'] ?? '')); $specialization=trim((string)($_POST['specialization'] ?? '')); $experience=trim((string)($_POST['experience'] ?? '')); $brands=trim((string)($_POST['brands'] ?? '')); $area=trim((string)($_POST['area'] ?? '')); $description=trim((string)($_POST['description'] ?? ''));
    if($name===''||$email===''||$phone===''||$specialization===''||$experience==='') $errors[]='Заполните ФИО, email, телефон, специализацию и опыт.';
    elseif(!filter_var($email,FILTER_VALIDATE_EMAIL)) $errors[]='Введите корректный email.';
    else { $photo=app_upload_image('photo','master-application'); db()->prepare('INSERT INTO master_applications (name,email,phone,photo,specialization,experience,brands,area,description) VALUES (:name,:email,:phone,:photo,:specialization,:experience,:brands,:area,:description)')->execute([':name'=>$name,':email'=>$email,':phone'=>$phone,':photo'=>$photo,':specialization'=>$specialization,':experience'=>$experience,':brands'=>$brands ?: null,':area'=>$area ?: null,':description'=>$description ?: null]); $done=true; }
  }
}
require_once __DIR__ . '/includes/header.php'; require_once __DIR__ . '/includes/layout.php'; render_site_header('apply'); ?>
<main><section class="pageLead"><div class="container pageLead__grid"><div><span class="sectionLabel">Для специалистов</span><h1>Анкета мастера</h1><p>Эта форма не мешает клиентам: на странице мастеров она открывается отдельной кнопкой «+». Анкету увидит только администратор.</p></div><div class="pageLead__card"><b>+</b><span>После принятия админом карточка мастера появится на сайте автоматически.</span></div></div></section><section class="screenSection"><div class="container"><?php if($done): ?><div class="contentPanel"><h2>Анкета отправлена</h2><p>Администратор рассмотрит заявку. Если вас примут, на email придут логин и временный пароль для входа в кабинет мастера.</p><a class="ghostButton" href="masters.php">Вернуться к мастерам</a></div><?php else: ?><?php if($errors): ?><div class="notice bad"><?php foreach($errors as $e): ?><div><?= h($e) ?></div><?php endforeach; ?></div><?php endif; ?><form class="leadForm masterApplyForm" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><label>ФИО<input name="name" required placeholder="Иван Иванов"></label><label>Email<input name="email" type="email" required placeholder="master@example.kz"></label><label>Телефон<input name="phone" required placeholder="+7 ___ ___ __ __"></label><label>Фото<input name="photo" type="file" accept="image/*"></label><label>Мастер по...<input name="specialization" required placeholder="Холодильникам / стиральным машинам"></label><label>Опыт<input name="experience" required placeholder="5 лет"></label><label>Районы<input name="area" placeholder="Бостандыкский, Алмалинский"></label><label>Бренды<input name="brands" placeholder="LG, Samsung, Bosch"></label><label class="wide">О себе<textarea name="description" placeholder="Какие работы выполняете, есть ли транспорт, какие условия"></textarea></label><button class="primaryButton" type="submit">Отправить анкету мастера</button></form><?php endif; ?></div></section></main><?php render_site_footer($services); require_once __DIR__ . '/includes/footer.php'; ?>
